[features]
seeds = false
skip-lint = false
[programs.localnet]
atbash_program = "H7ZkmfbuFeMGWpo78N1vfpqmzxTrRUAvP7VmqEBTxzyA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/desnet_dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
