[features]
seeds = false
skip-lint = false
[programs.localnet]
atbash_program = "UjBYSytrhiqA4vV8NQGL13a59UJKTPgUmAs6fH1dhwm"

[programs.devnet]
atbash_program = "UjBYSytrhiqA4vV8NQGL13a59UJKTPgUmAs6fH1dhwm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/desnet_dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
